[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0D78F2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 50
port = 8501

[logger]
level = "info"
